{
	"version": 1726715227,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/tiledbackground.png",
		"images/bin-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/waste-sheet0.png",
		"images/waste-sheet1.png",
		"images/waste2-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/p1-sheet0.png",
		"images/p2-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/sprite10-sheet0.png",
		"media/click.m4a",
		"media/click.ogg",
		"media/collect gem.m4a",
		"media/collect gem.ogg",
		"media/hit.m4a",
		"media/hit.ogg",
		"media/snapsave.io-_non-copyrighted-music_-neutrin05-a-new-beginning-_drum-and-bass_-_320-kbps__1.ogg",
		"media/snapsave.io-_non-copyrighted-music_-neutrin05-a-new-beginning-_drum-and-bass_-_320-kbps_.m4a",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}